  
name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign issues and pull requests with `bug` label to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/orgs/GMTStudios/projects/2'
        column_name: 'Needs triage'

  assign_central_project:
    runs-on: ubuntu-latest
    name: Assign to Central Project
    steps:
    - name: Assign issues and pull requests with `bug` label to project 5
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'bug')
      with:
        project: 'https://github.com/orgs/GMTStudios/projects/5'
        column_name: 'Bug Reports'